
import os;
from pathlib import Path;
import pandas as pd;

import mrkUtils

def toMRK(autoannotations_path, mrkFilePath):

    # Create .mrk file if it doesn't exist
    os.makedirs(os.path.dirname(mrkFilePath), exist_ok=True)
    fle = Path(mrkFilePath)
    fle.touch(exist_ok=True)
    
    # HANDLE AUTOMATIC ANNOTATIONS
    mrks = get(autoannotations_path, 'mrk')

    # Write to the appropriate .mrk file
    mrkUtils.write(mrkFilePath, mrks)


def get(autoannotations_path, type = 'all'):
    try:
        # Get auto-annotations file
        auto_read = pd.read_excel(autoannotations_path)

        # Organize as a marker array
        fileinfo = []

        for header, row in auto_read.iterrows():
            if (type == 'mrk'): info = [row['label'], 0, row['onset'], row['duration']]
            else: info = [row['label'], 0, row['onset'], row['duration'], row['channel'], row['confidence']]

            fileinfo.append(info)

        return fileinfo

    except Exception as e:
        print("Error: No autogenerated annotations:", autoannotations_path, e)
